formatter: "markdown" # this is required

header-from: main.tf

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: ["all"]


output:
  file: README.md
  mode: inject

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
